import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {webcrypto} from 'node:crypto';
import {existsSync} from 'node:fs';
const path = new URL('../ui/browser_identity.mjs', import.meta.url);
assert.ok(existsSync(path), 'Browser identity must survive reload independently of display names');
const {default: render} = await import(path);
globalThis.crypto = webcrypto;
let stored = null;
globalThis.localStorage = {getItem:()=>stored, setItem:(_key,value)=>{stored=value;}};
let first;
render({data:{},setStateValue:(_key,value)=>{first=value;}});
assert.equal(first.persisted, true);
assert.match(first.token, /^[A-Za-z0-9_-]{43}$/);
let second;
render({data:{},setStateValue:(_key,value)=>{second=value;}});
assert.equal(second.token, first.token, 'Reload must recover the same owner');
let sent = false;
render({data:{identity:first},setStateValue:()=>{sent=true;}});
assert.equal(sent,false,'Rerenders must not loop');
globalThis.localStorage = {getItem:()=>{throw Error('blocked');}};
let temporary;
render({data:{},setStateValue:(_key,value)=>{temporary=value;}});
assert.equal(temporary.persisted,false);
assert.notEqual(temporary.token,first.token);
console.log('Browser identity persistence, reload and blocked-storage tests: PASS');
